
spring:
  application:
    name: Config-Dev
eureka:
  instance:
    hostname: localhost
    ip-address: ture
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
